use_frameworks!

platform :ios, '10.0'

target 'QUIAlertController_Example' do
  pod 'QUIAlertController', :path => '../'

  target 'QUIAlertController_Tests' do
    inherit! :search_paths

    
  end
end
